### ISSUE TITLE
cannot read property 'sign' of null

### ISSUE THREAD

**Issue by TomBuyvoets** [BunqCommunity/bunqJSClient#22]
Ik probeer voor het eerst een simpel programma te schrijven om alle accounts op te halen. 
Ik krijg een error wanneer ik het probeer te draaien met `node index.js` 

Dit is mij code:
``` javascript
const BunqJsClient = require("@bunq-community/bunq-js-client").default;
const bunqClient = new BunqJsClient();

const ENCRYPTION_KEY = "lQF2p2LNIVPw2XcrxAxYvhLR6pWONWb4";
const API_KEY = "=== api key ===";
const DEVICE_NAME = "Tom server";
const ENVIRONMENT = "PRODUCTION";
const PERMITTED_IPS = [];

const setup = async () => {
    await bunqClient.run(API_KEY, PERMITTED_IPS, ENVIRONMENT, ENCRYPTION_KEY)
        .catch(error =>{
            throw error;
        });

    await bunqClient.install()
        .catch(error => {
            throw error;
        });

    await bunqClient.registerDevice(DEVICE_NAME)
        .catch(error => {
            throw error;
        });

    await bunqClient.registerSession()
        .catch(error => {
            throw error;
        });
}

setup();

const getMonetaryAccounts = async userid => {
    // get accounts
    const accounts = await bunqClient.api.monetaryAccount
        .list(userid)
        .catch(error => {
            throw error;
        });

    return accounts;
};

console.log(getMonetaryAccounts());
```

Ik krijg de volgende error.

Promise { <pending> }
TypeError: Cannot read property 'sign' of null
    at Object.exports.signString (/Users/tom/Projects/bunq-api/node_modules/@bunq-community/bunq-js-client/dist/Crypto/Sha256.js:43:39)
    at ApiAdapter.signRequest (/Users/tom/Projects/bunq-api/node_modules/@bunq-community/bunq-js-client/dist/ApiAdapter.js:256:31)
    at ApiAdapter.request (/Users/tom/Projects/bunq-api/node_modules/@bunq-community/bunq-js-client/dist/ApiAdapter.js:106:42)
    at ApiAdapter.get (/Users/tom/Projects/bunq-api/node_modules/@bunq-community/bunq-js-client/dist/ApiAdapter.js:34:37)
    at Object.limiter.run [as callable] (/Users/tom/Projects/bunq-api/node_modules/@bunq-community/bunq-js-client/dist/Api/MonetaryAccount.js:42:72)
    at RequestLimiter.check (/Users/tom/Projects/bunq-api/node_modules/@bunq-community/bunq-js-client/dist/RequestLimiter.js:48:50)
    at RequestLimiter.run (/Users/tom/Projects/bunq-api/node_modules/@bunq-community/bunq-js-client/dist/RequestLimiter.js:94:18)
    at MonetaryAccount.list (/Users/tom/Projects/bunq-api/node_modules/@bunq-community/bunq-js-client/dist/Api/MonetaryAccount.js:42:40)
    at getMonetaryAccounts (/Users/tom/Projects/bunq-api/index.js:37:10)
    at Object.<anonymous> (/Users/tom/Projects/bunq-api/index.js:45:13)
(node:29061) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'sign' of null
(node:29061) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

mijn setup:
* node 8.9.3
* dit package: 0.22.3
* Os: Mac OS Sierra

Iemand een suggestie waaraan dit kan liggen?

Alvast bedankt!

**Comment by Crecket** [comment]
Ik hoop dat de API key die je daar hebt staan niet je echte key is? En zo ja disable hem dan zo snel mogelijk in de bunq app.

En als je deze cliënt in NodeJS wilt gebruiken moet je een custom storage interface gebruiken. Standaard is deze namelijk bedoeld voor de browser. Een custom store kan bijvoorbeeld dit zijn: [custom_store.js](https://github.com/BunqCommunity/bunqJSClient/blob/master/examples/custom_store.js)
